### ISSUE TITLE
 Notification UI for version Upgrade

### ISSUE THREAD

**Issue by rajmbcoderx** [k8-proxy/k8-proxy-desktop#145]
Notification UI for version Upgrade

**Comment by kumarsudhish** [comment]
Verified this CR and observed that it has been fixed.
Hence marking this as Closed.

**Comment by kumarsudhish** [comment]
Issue moved to [k8-proxy/glasswall-desktop #23](https://github.com/k8-proxy/glasswall-desktop/issues/23) via [**ZenHub**](https://www.zenhub.com/)
