### ISSUE TITLE
Identify all use cases 

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-proxy-desktop#2]

**Comment by jcanales** [comment]
- List of all gatsby websites

**Comment by dtollaku** [comment]
@b24repo can we have here all use cases before we close this issue?

**Comment by b24repo** [comment]
Use-Case-01 Integrate filetrust git browser 
Use-Case-2 Integrate file-drop
Use-Case-3 - Integrate k8-* project UIs
Use-Case-4 - Integrate slackbot
