### ISSUE TITLE
Add option to View forensic-workbench.com

### ISSUE THREAD

**Issue by b24repo** [k8-proxy/k8-proxy-desktop#32]
a task to display/view https://forensic-workbench.com/'

**Comment by rajmbcoderx** [comment]
Added the site though there is a lag in the display. Doing analysis in identifying the lag reason

**Comment by b24repo** [comment]
Lag in loading the view.

**Comment by rajmbcoderx** [comment]
Fixed the self-signed certificate issue and added a loader to optimize the UX for this
