### ISSUE TITLE
Verify and analyse existing release package

### ISSUE THREAD

**Issue by b24repo** [k8-proxy/k8-proxy-desktop#52]

**Comment by kumarsudhish** [comment]
Worked on k8-proxy-desktop and figured out few observations and improvements.
And here is the consolidated sheet listing down all observations & improvement. https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=0
**Summary**
1. Observations in k8-proxy-desktop : 14
2. Improvement in k8-proxy-desktop : 2
