### ISSUE TITLE
Removed download options from Welcome page 

### ISSUE THREAD

**Issue by rajmbcoderx** [k8-proxy/k8-proxy-desktop#66]
As per demo feedback
Removed download options from Welcome page

**Comment by kumarsudhish** [comment]
Hi @All, 
Today would be verifying this.

**Comment by kumarsudhish** [comment]
Verified this issue in latest code under @rajmbcoderx code branch and observed that has been fixed.
![image](https://user-images.githubusercontent.com/71662255/94413424-b186f280-0198-11eb-98bc-b814d27e127c.png)

Hence this issue has been fixed.
