### ISSUE TITLE
Remove navigation items from Menubar and use the top bar for this 

### ISSUE THREAD

**Issue by rajmbcoderx** [k8-proxy/k8-proxy-desktop#67]
As per demo feedback 
Remove navigation items from Menubar and use the top bar for this

**Comment by kumarsudhish** [comment]
Verified this issue on @rajmbcoderx code repository and observed that **Report an issue** option and **Home** has been added in the header and removed from the Menubar

![image](https://user-images.githubusercontent.com/71662255/94574729-1887d280-0291-11eb-88a0-7ae95bf42687.png)
