### ISSUE TITLE
Create workflow and diagram for proxy-desktop, git-visualization and their release interactions

### ISSUE THREAD

**Issue by gmuditdce** [k8-proxy/k8-proxy-desktop#99]
Create workflow and diagram for proxy-desktop, git-visualization and their release interactions

**Comment by rajmbcoderx** [comment]
@dinis-cruz-gw here is a diagram and workflow on how we plan to integrate jupyter and git-visualization (from the repo at https://github.com/k8-proxy/k8-data-visualization)
![image](https://user-images.githubusercontent.com/20489970/94840749-8ae5e780-0436-11eb-8050-31d09fff8966.png)
